# Generated by Django 4.2.1 on 2023-05-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.IntegerField(null=True),
        ),
    ]
